## NUMPY

수치해석, 수학적처리, 통계 등을 위한 모듈

> !pip install numpy

In [1]:
%pip install numpy


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Users\user\BigData_2023\venv\Lib\site-packages
Requires: 
Required-by: pandas


In [3]:
!pip install matplotlib

  Using cached matplotlib-3.7.2-cp311-cp311-win_amd64.whl (7.5 MB)
  Using cached contourpy-1.1.0-cp311-cp311-win_amd64.whl (470 kB)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
     ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
      --------------------------------------- 0.0/2.1 MB 1.4 MB/s eta 0:00:02
     -- ------------------------------------- 0.1/2.1 MB 1.8 MB/s eta 0:00:02
     --- ------------------------------------ 0.2/2.1 MB 1.8 MB/s eta 0:00:02
     ----- ---------------------------------- 0.3/2.1 MB 1.7 MB/s eta 0:00:02
     ------ --------------------------------- 0.4/2.1 MB 1.7 MB/s eta 0:00:02
     -------- ------------------------------- 0.5/2.1 MB 1.8 MB/s eta 0:00:01
     ---------- ----------------------------- 0.6/2.1 MB 1.9 MB/s eta 0:00:01
     ------------- -------------------------- 0.7/2.1 MB 2.0 MB/s eta 0:00:01
     --------------- ------------------------ 0.8/2.1 MB 2.0 MB/s eta 0:00:01
     ----------------- ----------------


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np

##### Numpy 사용 이유

- python 리스트를 만들고 사용처리가 만약 1,000,000 건이라면  -> 200ms 
- numpy 배열 1,000,000 건 배열 만들고 사용처리 - 대략 20ms (1/10배)

In [8]:
py_list = list(range(1_000_000))    # 100만건 리스트
np_arr = np.array(1_000_000)    # 100만건 배열

In [10]:
%timeit for _ in range(10): py_list2 = py_list *100

8.84 s ± 327 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


##### numpy 로 배열 생성, 연산

- 파이널 리스트 +, * 뿐

- 행렬(벡터) 연산이 필요하면 numpy로 형변환 후 처리 가능

##### numpy 연산

In [11]:
list2 = [4,5,6]
np_arr1 = np.array(list2)

In [12]:
np_arr1

array([4, 5, 6])

In [13]:
np_arr2 = np.array([[1,2,3], [4,5,6]])
np_arr2 

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
list1 = [1,2,3]

In [15]:
np_arr3 = np.array(list1)
np_arr4 = np.array(list2)

In [16]:
np_arr3+np_arr4

array([5, 7, 9])

In [18]:
np_arr4-np_arr3

array([3, 3, 3])

In [19]:
np_arr3*np_arr4

array([ 4, 10, 18])

In [20]:
np_arr3/np_arr4

array([0.25, 0.4 , 0.5 ])

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.random.randn(50)

array([ 1.37444658, -0.80548974,  0.13288673, -0.59924255, -1.76258157,
       -0.94409153, -0.18301148, -1.47407982,  1.21694578, -0.72054345,
       -0.09134228,  0.3462187 , -0.39344227, -0.75380659,  0.4659778 ,
       -0.68598818, -0.89668057, -0.12683954,  0.25502067,  0.97248075,
        0.58055629, -3.10266642, -0.41814851,  0.18462728,  0.08980998,
       -1.15435968,  1.1538493 ,  2.90486242,  0.13825296, -1.66735751,
        1.43254224,  2.04131309, -0.59586917,  0.78838513, -1.21772035,
        0.39166624, -1.97311775, -0.88010475,  0.16317316,  0.26817818,
       -0.57653117, -1.59168932,  0.68083216,  0.25371625, -1.40973186,
        0.30012144,  0.69817491, -0.28813562, -0.75412874,  0.96219967])

In [24]:
np.random.randn(5,4)

array([[ 0.86232965,  0.99368752, -1.5105834 , -0.60655844],
       [ 0.75437575,  0.98102223,  1.23330628,  2.22582159],
       [-1.24919666, -2.08639099, -1.67766515,  1.07996361],
       [-1.09044805,  0.6335709 ,  0.22070992,  0.49314542],
       [ 0.08587924, -0.28752411, -0.10716599, -0.30582349]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
(np_arr3+np_arr4) < 9

array([ True,  True, False])

In [28]:
(np_arr3+np_arr4) == 9

array([False, False,  True])

##### Numpu 속성

In [29]:
# 1차원 배열은 열값이 앞에 나옴
np_arr1.shape

(3,)

In [30]:
# 2차원 배열은 행, 열 순 
np_arr2.shape

(2, 3)

In [32]:
np_arr2.dtype

dtype('int32')

In [33]:
np_arr2.T.shape

(3, 2)

# 기타 함수

In [35]:
np_arr5 = np.arange(10)
np_arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np_arr5.mean()

4.5

In [37]:
np_arr5.sum()

45

In [39]:
# 적층형 합계
np_arr5.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [40]:
np_arr6 = np.random.rand(10)
np_arr6

array([0.75057428, 0.25939549, 0.34395101, 0.56324886, 0.42217224,
       0.27689371, 0.56941361, 0.23217501, 0.81949454, 0.15830424])

In [44]:
np_arr6=np_arr6*10
np_arr6

array([75.05742796, 25.93954929, 34.39510056, 56.32488602, 42.21722362,
       27.68937127, 56.94136095, 23.217501  , 81.94945422, 15.83042411])

In [46]:
# 오름차순 정렬
np_arr6.sort()
np_arr6

array([15.83042411, 23.217501  , 25.93954929, 27.68937127, 34.39510056,
       42.21722362, 56.32488602, 56.94136095, 75.05742796, 81.94945422])

In [47]:
-np.sort(-np_arr6)

array([81.94945422, 75.05742796, 56.94136095, 56.32488602, 42.21722362,
       34.39510056, 27.68937127, 25.93954929, 23.217501  , 15.83042411])